### 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


Purpose of NumPy

1. Efficient Array Handling:

Purpose: NumPy provides a high-performance array object called ndarray which is used to store and manipulate large datasets efficiently.

Advantage: The ndarray object supports vectorized operations, which means that operations can be applied to entire arrays without explicit loops, leading to more concise and readable code.

2. Mathematical Functions:

Purpose: NumPy includes a wide range of mathematical functions, such as linear algebra operations, statistical functions, and more.


Advantage: These functions are implemented in C and optimized for performance, making them significantly faster than equivalent operations written in pure Python.

3.Integration with Other Libraries:

Purpose: NumPy serves as the foundation for many other scientific computing libraries, such as SciPy, pandas, and scikit-learn.

Advantage: It provides a standard interface for numerical data, allowing for seamless integration and interoperability with other libraries in the Python ecosystem.


4. Broadcasting:

Purpose: NumPy supports broadcasting, a technique that allows operations to be performed on arrays of different shapes without explicit replication of data.

Advantage: Broadcasting simplifies code and improves performance by eliminating the need for manually reshaping arrays or performing redundant calculations.


5.Memory Efficiency:


Purpose: NumPy arrays use less memory compared to traditional Python lists and have a fixed type for each element.

Advantage: This memory efficiency is crucial for handling large datasets and performing computations that require substantial memory.

NumPy enhances Python’s capabilities for numerical operations by providing:

High-performance array handling

Vectorized operations


Broad range of mathematical functions

Efficient memory use


Support for multidimensional data

### 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


np.mean()

Purpose: Computes the arithmetic mean of the elements in an array.

Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)
print("Mean:", mean_value)


Mean: 3.0


np.average()

Purpose: Computes the weighted average of array elements, with an optional weights parameter.

Syntax: np.average(a, axis=None, weights=None, returned=False)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])
average_value = np.average(arr, weights=weights)
print("Weighted Average:", average_value)


Comparison

1.Basic Calculation:

np.mean() always calculates the arithmetic mean of the elements.

np.average() can calculate a weighted average if weights are provided.

2. Weights:

np.mean() does not support weights.

np.average() supports weights, allowing for more flexible calculations where some data points contribute more to the average than others.

3. Return Value:

np.mean() always returns the mean of the array.

np.average() can return a tuple if returned=True, including both the weighted average and the sum of weights.

4.Usage:

Use np.mean() when you need a simple arithmetic mean of the data.

Use np.average() when you need a weighted average where some elements should have more influence on the result than others.


### 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.


Reversing a 1D Array

In [2]:
import numpy as np

# Creating a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Reversing the array
reversed_arr = arr[::-1]

print("Original array:", arr)
print("Reversed array:", reversed_arr)


Original array: [1 2 3 4 5]
Reversed array: [5 4 3 2 1]


Reversing a 2D Array

1. Reversing along the rows (axis 0):

In [3]:
import numpy as np

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along rows (axis 0)
reversed_rows = arr_2d[::-1, :]

print("Original 2D array:\n", arr_2d)
print("Reversed along rows:\n", reversed_rows)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


2. Reversing along the columns (axis 1):

In [4]:
import numpy as np

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along columns (axis 1)
reversed_columns = arr_2d[:, ::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed along columns:\n", reversed_columns)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


3. Reversing along both axes (both rows and columns):



In [5]:
import numpy as np

# Creating a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reversing along both rows and columns
reversed_both = arr_2d[::-1, ::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed along both axes:\n", reversed_both)


Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along both axes:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


Determining the Data Type of Elements in a NumPy Array

In [6]:
import numpy as np

# Creating a NumPy array with integer data
arr_int = np.array([1, 2, 3, 4])
print("Data type of arr_int:", arr_int.dtype)

# Creating a NumPy array with float data
arr_float = np.array([1.0, 2.0, 3.0, 4.0])
print("Data type of arr_float:", arr_float.dtype)

# Creating a NumPy array with complex data
arr_complex = np.array([1+2j, 3+4j])
print("Data type of arr_complex:", arr_complex.dtype)


Data type of arr_int: int64
Data type of arr_float: float64
Data type of arr_complex: complex128


Importance of Data Types in Memory Management and Performance


1. Memory Management:

Storage Size: Different data types require different amounts of memory. For example, an int32 takes 4 bytes, while an int64 takes 8 bytes. Choosing the appropriate data type helps in reducing memory usage. For instance, using float32 instead of float64 can save memory if the precision provided by float32 is sufficient for your calculations.


Data Alignment: Data types also affect how data is aligned in memory, which can influence performance. Smaller data types may lead to less memory overhead and better cache utilization.

2. Performance:

Computation Speed: The choice of data type affects the speed of mathematical operations. For instance, operations on float32 arrays may be faster than on float64 arrays due to reduced computational complexity. However, this is also dependent on hardware and whether it has specialized instructions for certain data types.

Vectorization: NumPy is optimized for operations on arrays. Using the correct data type ensures that these operations can be vectorized efficiently. For example, operations on integer arrays can be faster than on floating-point arrays due to less complexity in handling integer arithmetic.

Precision vs. Speed: Choosing a data type involves a trade-off between precision and speed. For example, float64 provides higher precision than float32, but operations on float32 can be faster and use less memory. Selecting the right data type depends on the requirements of your application.

### 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray in NumPy

Key Features of ndarray:

1. Multidimensional:

ndarray supports arrays of any number of dimensions. A 1D array is a vector, a 2D array is a matrix, and arrays can extend to higher dimensions.

2. Homogeneous Elements:


All elements in a ndarray must be of the same type, which allows for efficient memory usage and fast computation.

3. Efficient Storage and Computation:

NumPy arrays are stored more efficiently than Python lists and support vectorized operations, which can lead to significant performance improvements for numerical computations.

4. Element-wise Operations:

NumPy supports element-wise operations such as addition, multiplication, and more, directly on arrays without the need for explicit loops.


5. Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes and sizes without needing explicit replication of data.

6. Shape and Size Attributes:

7. Indexing and Slicing:


ndarray supports advanced indexing and slicing capabilities, allowing for more complex data manipulation than standard Python lists.


8.Efficient Memory Usage:

NumPy arrays use less memory compared to Python lists due to contiguous memory storage and efficient internal representation.


In [8]:
import numpy as np

# Creating a 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data type:", arr.dtype)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Size: 9
Data type: int64


Comparison with Standard Python Lists

1. Dimensionality:

NumPy Arrays: Support multidimensional arrays.

Python Lists: Support only one-dimensional lists (nested lists can simulate multidimensional structures but are less efficient).


2. Data Type Consistency:

NumPy Arrays: Elements must be of the same type.

Python Lists: Can contain elements of different types.

3. Performance:

NumPy Arrays: Generally more efficient for large-scale numerical computations due to optimized memory layout and vectorized operations.

Python Lists: Slower for numerical operations, as operations are performed in Python rather than in optimized C code.

4.Operations:

NumPy Arrays: Support element-wise operations, broadcasting, and more sophisticated mathematical functions.

Python Lists: Do not support element-wise operations directly and require explicit loops for such operations.

5.Memory Efficiency:

NumPy Arrays: Use less memory and provide more efficient storage by using contiguous memory.

Python Lists: Use more memory as they store type information and are less efficient for large datasets.

### 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

1. Memory Efficiency

NumPy Arrays:

Contiguous Memory Allocation: NumPy arrays store elements in contiguous blocks of memory, which allows for more efficient memory access and reduced overhead.


Data Type Consistency: All elements in a NumPy array have the same data type, which reduces the memory footprint compared to Python lists, where each element is a separate object with its own metadata.

Python Lists:

Overhead Per Element: Each element in a Python list is a reference to a separate object, which includes additional overhead. This can lead to increased memory consumption, especially with large datasets.

Non-Contiguous Storage: Python lists are stored as arrays of pointers to objects, leading to non-contiguous memory access and potential inefficiencies.


2. Performance of Operations

NumPy Arrays:

Vectorization: NumPy arrays support vectorized operations, where operations are applied to entire arrays without explicit loops in Python. This leverages low-level, optimized C and Fortran libraries, resulting in significant speedups.

Broadcasting: NumPy's broadcasting allows for efficient operations on arrays of different shapes without the need for replication, thus reducing computation time.


Optimized Internal Implementations: NumPy operations are implemented in C, allowing for fast execution of mathematical functions, reductions, and aggregations.

Python Lists:

Element-wise Operations: Performing element-wise operations on Python lists typically requires explicit loops in Python, which are slower compared to vectorized operations in NumPy.

Lack of Broadcasting: Python lists do not natively support broadcasting, making operations on differently shaped data less efficient and more cumbersome to implement.


3. Computational Complexity

NumPy Arrays:

Efficient Algorithms: NumPy provides highly optimized algorithms for numerical computations. For instance, functions for matrix multiplication and linear algebra are implemented with optimized libraries like BLAS and LAPACK.

Parallelization: NumPy can leverage parallel computation for certain operations, especially when using libraries like MKL (Math Kernel Library).

Python Lists:

Higher Computational Overhead: Operations on Python lists involve more overhead due to the need for Python-level loops and additional function calls, leading to slower performance for large datasets.

### 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and  output.


vstack()

Purpose:

vstack() (vertical stack) stacks arrays vertically along the rows. It concatenates arrays along the vertical axis, effectively increasing the number of rows while keeping the number of columns unchanged.

Usage:

All arrays must have the same number of columns.

It combines arrays by appending them one on top of the other.


In [9]:
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:\n", result_vstack)


Result of vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


hstack()

Purpose:

hstack() (horizontal stack) stacks arrays horizontally along the columns. It concatenates arrays along the horizontal axis, effectively increasing the number of columns while keeping the number of rows unchanged.


Usage:

All arrays must have the same number of rows.


It combines arrays by appending them side by side.


In [10]:
import numpy as np

# Define two 2D arrays
array1 = np.array([[1, 2],
                   [3, 4]])

array2 = np.array([[5, 6],
                   [7, 8]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:\n", result_hstack)


Result of hstack:
 [[1 2 5 6]
 [3 4 7 8]]


### 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.


fliplr()

Purpose:

fliplr() (flip left-right) flips an array horizontally, i.e., it reverses the order of elements along the second axis (axis 1). This function is applicable to 2D arrays and higher-dimensional arrays where the second axis is present.

Usage:

For a 2D array, fliplr() reverses the order of elements in each row.

For arrays with more than two dimensions, fliplr() operates on the second axis of the array.


In [12]:
import numpy as np

# Define a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip left-right
result_fliplr = np.fliplr(array_2d)

print("Original Array:\n", array_2d)
print("Result of fliplr:\n", result_fliplr)


Original Array:
 [[1 2 3]
 [4 5 6]]
Result of fliplr:
 [[3 2 1]
 [6 5 4]]


flipud()

Purpose:

flipud() (flip up-down) flips an array vertically, i.e., it reverses the order of elements along the first axis (axis 0). This function is applicable to 2D arrays and higher-dimensional arrays where the first axis is present.

Usage:

For a 2D array, flipud() reverses the order of rows.

For arrays with more than two dimensions, flipud() operates on the first axis of the array.


In [13]:
import numpy as np

# Define a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip up-down
result_flipud = np.flipud(array_2d)

print("Original Array:\n", array_2d)
print("Result of flipud:\n", result_flipud)


Original Array:
 [[1 2 3]
 [4 5 6]]
Result of flipud:
 [[4 5 6]
 [1 2 3]]


### 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Functionality of array_split()

In [ ]:
numpy.array_split(ary, indices_or_sections, axis=0)


Handling Uneven Splits

xample 1: Splitting into Equal Parts

In [15]:
import numpy as np

# Define an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 3 equal parts
result = np.array_split(array, 3)

print("Array:", array)
print("Result of array_split into 3 parts:", result)


Array: [1 2 3 4 5 6 7 8 9]
Result of array_split into 3 parts: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


Example 2: Uneven Split

In [16]:
import numpy as np

# Define an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array into 4 parts
result = np.array_split(array, 4)

print("Array:", array)
print("Result of array_split into 4 parts:", result)


Array: [1 2 3 4 5 6 7 8 9]
Result of array_split into 4 parts: [array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


Example 3: Splitting with Specific Indices

In [17]:
import numpy as np

# Define an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Split the array at indices 2 and 5
result = np.array_split(array, [2, 5])

print("Array:", array)
print("Result of array_split at indices 2 and 5:", result)


Array: [1 2 3 4 5 6 7 8 9]
Result of array_split at indices 2 and 5: [array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]


### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?


Vectorization

Concept:

Vectorization refers to the practice of replacing explicit loops with vectorized operations on NumPy arrays. Instead of iterating over elements in a loop and applying operations one by one, vectorization allows you to apply operations to entire arrays at once.

Benefits:

Performance: Vectorized operations are executed in compiled code, which is much faster than interpreted Python loops. NumPy utilizes optimized C and Fortran libraries to perform these operations efficiently.

Simplicity: Code becomes more concise and readable, as vectorized operations can be expressed in a more straightforward manner.

Without vectorization:

In [18]:
import numpy as np

# Define arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Initialize an empty array for results
result = np.empty_like(a)

# Perform element-wise addition using a loop
for i in range(len(a)):
    result[i] = a[i] + b[i]

print("Result without vectorization:", result)


Result without vectorization: [ 6  8 10 12]


With vectorization:

In [19]:
import numpy as np

# Define arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Perform element-wise addition using vectorization
result = a + b

print("Result with vectorization:", result)


Result with vectorization: [ 6  8 10 12]


Broadcasting

Concept:

Broadcasting is a technique used to perform element-wise operations on arrays of different shapes. It allows NumPy to perform operations on arrays with different dimensions by automatically expanding the smaller array to match the shape of the larger array.


Rules:

Dimension Compatibility: The dimensions of the arrays being operated on must be compatible. Two dimensions are compatible if they are equal, or one of them is 1.

Broadcasting: NumPy implicitly broadcasts the smaller array to match the shape of the larger array without making copies of data.

In [20]:
import numpy as np

# Define a 2D array and a 1D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Add the 1D array to each row of the 2D array
result = array_2d + array_1d

print("Result with broadcasting:\n", result)


Result with broadcasting:
 [[11 22 33]
 [14 25 36]]


### 1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [21]:
import numpy as np

# Step 1: Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Step 2: Interchange rows and columns (transpose the array)
transposed_array = array.T

print("Original Array:\n", array)
print("\nTransposed Array:\n", transposed_array)


Original Array:
 [[81 21 10]
 [95  8 84]
 [67  6 65]]

Transposed Array:
 [[81 95 67]
 [21  8  6]
 [10 84 65]]


 ### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [22]:
import numpy as np

# Step 1: Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Step 2: Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

print("Original 1D Array:\n", array_1d)
print("\nReshaped 2x5 Array:\n", array_2x5)
print("\nReshaped 5x2 Array:\n", array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [23]:
import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around the 4x4 array
# 'pad_width' specifies the number of rows/columns to add on each side
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:\n", array_4x4)
print("\n6x6 Array with Border:\n", array_with_border)


Original 4x4 Array:
 [[0.23898405 0.15857191 0.4972909  0.74528428]
 [0.17036456 0.49765941 0.52641254 0.34944323]
 [0.38619416 0.45007945 0.20993028 0.90043457]
 [0.94468585 0.70479383 0.90610648 0.43626451]]

6x6 Array with Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.23898405 0.15857191 0.4972909  0.74528428 0.        ]
 [0.         0.17036456 0.49765941 0.52641254 0.34944323 0.        ]
 [0.         0.38619416 0.45007945 0.20993028 0.90043457 0.        ]
 [0.         0.94468585 0.70479383 0.90610648 0.43626451 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [24]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

print("Array from 10 to 60 with a step of 5:\n", array)


Array from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


In [25]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)
capitalize_array = np.char.capitalize(array)

print("Original Array:\n", array)
print("\nUppercase:\n", uppercase_array)
print("\nLowercase:\n", lowercase_array)
print("\nTitle Case:\n", titlecase_array)
print("\nCapitalize:\n", capitalize_array)


Original Array:
 ['python' 'numpy' 'pandas']

Uppercase:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
 ['python' 'numpy' 'pandas']

Title Case:
 ['Python' 'Numpy' 'Pandas']

Capitalize:
 ['Python' 'Numpy' 'Pandas']


 ### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [26]:
import numpy as np

# Generate a NumPy array of words
words_array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

print("Original Array:\n", words_array)
print("\nArray with Spaces Between Characters:\n", spaced_words_array)


Original Array:
 ['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [27]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[6, 5, 4], [3, 2, 1]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
# Adding a small value to avoid division by zero errors
division = array1 / (array2 + 1e-10)

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nElement-wise Addition:\n", addition)
print("\nElement-wise Subtraction:\n", subtraction)
print("\nElement-wise Multiplication:\n", multiplication)
print("\nElement-wise Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[6 5 4]
 [3 2 1]]

Element-wise Addition:
 [[7 7 7]
 [7 7 7]]

Element-wise Subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]

Element-wise Multiplication:
 [[ 6 10 12]
 [12 10  6]]

Element-wise Division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [28]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

print("5x5 Identity Matrix:\n", identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


In [29]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find and display all prime numbers in the array
prime_numbers = np.array([num for num in random_array if is_prime(num)])

print("Random Array:\n", random_array)
print("\nPrime Numbers:\n", prime_numbers)


Random Array:
 [735 494 622 559 255 181 454 628 277 597 626 982 925 648 990 433 361 435
 906 428 681 678 860 622 714 791 637 562 403 880 994 555 581  34 877 516
 359 678 194 553 835 830  22 810 554 957  46 332 704 444 898 367 349 951
 109 207 190 974 135 587 852 852 573 941  75 328 935 772 465 243 921 478
 700 888 673 473 147 144 612 685 218 988 399 723 311 403 902 474 209 873
 872 910 994 941  83  46 316 712 418 847]

Prime Numbers:
 [181 277 433 877 359 367 349 109 587 941 673 311 941  83]


### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly average


In [30]:
import numpy as np

# Generate random temperatures for 28 days
daily_temperatures = np.random.randint(20, 36, size=28)

# Reshape the array into a 2D array with 4 weeks (each week has 7 days)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Calculate the weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures:\n", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Averages:\n", weekly_averages)


Daily Temperatures:
 [23 27 22 21 32 35 29 29 32 29 32 21 29 20 25 32 20 21 35 33 20 32 29 28
 26 20 23 32]

Weekly Temperatures:
 [[23 27 22 21 32 35 29]
 [29 32 29 32 21 29 20]
 [25 32 20 21 35 33 20]
 [32 29 28 26 20 23 32]]

Weekly Averages:
 [27.         27.42857143 26.57142857 27.14285714]
